#cloud-config
ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCgDEqdveR1v6cBbSwU1ej69A86QJqbbFC3ZH074w7F6naqDLaF783HPFVOiIzcjtWBG6ohDrpZ6vPr4jgamxOL9kb8ZGRhTqYDsC3t5tivmCknrnYCMADPXLKvhGnfFFbq65WvuuRwT40cmoTQzW5/zd+KgP7yldKDFeFCIPyz3N9sZRyr/YAsluMVXP5BKFOuH1zn2BLAcUPSsHBPaCTcFajB7qAQNMR+gWubXfV8RUr4dp1OI4t33IeAZkEhbHhQieivkz1edFuEgaDDo/qaVJp+g5I2rY+asxbOIfJMSue6C5OnB0/GuxEmiO8e1ktgEmkYdz0N1qiN8ybPBdhwzGZepXhn8kDkIwHwDSdNXvbPJQdy/CrZ2fa6m4bUcsFhsBjw//Ke8yv6TJQv0OTUX4BsoScET+dWM91aoIiUM71K2nULYR4Vg6h0pIsrXT6l0wWXWL7W3uv8WVjHtTeNLBYKiKfhb7rqs+ws3NnNrLd3WO7fBmKd1hiRAoDiF8Nd7seh3baM6ORgBiBVnHutTQWQaUOX3H7PfsLLDk07cLQgDZoMwKNtsyDhCD492Di0RTY8WIrMNIgAsLtez0SEAtCyFPc5eolpuDaPwdMUAO1SYprIny9kCBehhKAhe6QgIeQmC7PvTffH08epp722gmnBfTMcfVNz9rYq3prgGw== dsaouda@gmail.com
hostname: rancher-vm1
rancher:  
  network:
    interfaces:
      eth0:
        dhcp: true
      eth1:
        address: 192.168.200.10/24
    dns:
      nameservers:
      - 8.8.8.8
      - 8.8.4.4